### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wackoisgod**

### CODE REVIEW

**Comment by netcode-ci-service** [comment]
@unityrfc merge

**Comment by netcode-ci-service** [comment]
Team member @netcode-ci-service has proposed to Merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once 0% of reviewers approve (Currently thats 0 of 0), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

**Comment by wackoisgod** [comment]
@unityrfc reviewed

**Comment by wackoisgod** [comment]
@unityrfc cancel

**Comment by netcode-ci-service** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/2#issuecomment-725769319). :bell:

**Comment by wackoisgod** [comment]
@unityrfc cancel

**Comment by netcode-ci-service** [comment]
wackoisgod proposal canceled

**Comment by wackoisgod** [comment]
@unityrfc merge

**Comment by netcode-ci-service** [comment]
Team member @wackoisgod has proposed to Merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once 0% of reviewers approve (Currently thats 0 of 0), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

**Comment by netcode-ci-service** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/2#issuecomment-725775948). :bell:

**Comment by wackoisgod** [comment]
d

**Comment by netcode-ci-service** [comment]
The final comment period, with a disposition to **Merge**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/2#issuecomment-725775948), is now **complete**.

As the automated representative of the RFC process, I would like to thank the author for their work and everyone else who contributed.

The RFC will be merged soon.

**Pull request merged**
