### PR TITLE
Create 0000-this-adawd-two-rfc.md

### PR DESCRIPTION
**Pull request by wackoisgod**
awdawdawd

### CODE REVIEW

**Comment by wackoisgod** [comment]
@rfcbot merge 

@rfcbot concern this is a test

**Comment by netcode-ci-service** [comment]
Team member @wackoisgod has proposed to Merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once 0% of reviewers approve (Currently thats 0 of 0), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

**Comment by wackoisgod** [comment]
@rfcbot resolved this is a test

**Comment by netcode-ci-service** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/6#issuecomment-739824111). :bell:

**Pull request merged**
