### PR TITLE
Create 0000-this-test-two-rfc.md

### PR DESCRIPTION
**Pull request by wackoisgod**
qwd

### CODE REVIEW

**Comment by wackoisgod** [comment]
@rfcbot merge

**Comment by netcode-ci-service** [comment]
Team member @wackoisgod has proposed to Merge this. The next step is review by the rest of the tagged team members:


No concerns currently listed.

Once 0% of reviewers approve (Currently thats 0 of 0), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

**Comment by netcode-ci-service** [comment]
:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/5#issuecomment-739812157). :bell:

**Comment by wackoisgod** [comment]
test

**Comment by netcode-ci-service** [comment]
The final comment period, with a disposition to **Merge**, as per the [review above](https://github.com/wackoisgod/AutomationTestRepo/pull/5#issuecomment-739812157), is now **complete**.

As the automated representative of the RFC process, I would like to thank the author for their work and everyone else who contributed.

The RFC will be merged soon.

**Pull request merged**
